<a href="https://colab.research.google.com/github/smithve-laf/smith-repository-notebook/blob/main/numpy_02_10_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In this notebook, we'll encounter a package for scientific computing in Python: NumPy.

**At the end of this notebook, you'll be able to:**
* Install and import packages for Python
* Create NumPy arrays
* Execute methods & access attributes of arrays


## Importing packages

Before we can use numpy, we need to import it. We can also nickname modules when we import them.

The convention is to import `numpy` as `np`.

In [ ]:
# Import packages, numpy is like a list on steriods. you can make really really big lists
import numpy as np

# Use whos 'magic command' to see available modules
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


## Numpy

**Numpy** is the fundamental package for scientific computing with Python. It'll allow us to work with bigger datasets more efficiently.

### Creating `numpy` arrays

A numpy **array** is a grid of values which are all the same type (they’re homogenous).

We can create a numpy array in a few different ways:

* from a Python list or tuples
* by using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, `empty`,`zeroes`, etc.
* reading data from files

In [ ]:
# Create a list
lst = [1,2,3,4,5]

# Make our list into an array - one dimension, (like our one row of data)
my_vector = np.array(lst)
print(type(my_vector))
print(my_vector)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
# If we give numpy a list of lists, it will create a matrix, two lists stacked on top of eachother. two rows 5 columns = matrix
#now the data has multiple dimensions, this one has two, rows and columns
my_matrix = np.array([lst,lst])
print(my_matrix)

[[1 2 3 4 5]
 [1 2 3 4 5]]


### Accessing attributes of numpy arrays

We can test shape and size either by looking at the attribute of the array, or by using the `shape()` and `size()` methods.

Other attributes that might be of interest are `ndim` and `dtype`.

In [ ]:
# Check the type of vector, int64 because they are integers (numbers). its int64 because 64 bits is the amount of memory python is giving the data
print(my_vector.dtype)

# Check the dimensions of matrix, we have 2
print(my_matrix.ndim)

int64
2


Array data type is decided upon creation of the array.

You can explicitly define the data type by using `dtype= ` when you use `np.array()`. You can set the dtype to be `int, float, complex, bool, object`, etc

In [ ]:
# my_matrix.dtype
#when you change the type of the array its now a complex, which means it has a real part and an imaginary parts. if you have an integer python is providing just number part
#if you make it a complex it shows the number part and the imaginary part, doubling it, doubling the memory it needs
my_complex_array = np.array([lst,lst],dtype='complex')
my_complex_array.dtype

dtype('complex128')

><b>Task:</b> Create an array of integers called `int_array` that is 2 rows x 3 columns. Access the shape and ndim attributes to confirm its size, and the dtype attribute to confirm that it is indeed an array of integers.



In [ ]:
# Your code here
list = [8, 9, 10]

vector = np.array(list)
int_array = np.array([list, list])

print(int_array)

print(int_array.ndim) #number of dimensions
print(int_array.dtype) #type = int64

print(int_array.shape) #shape, number of rows and columns


[[ 8  9 10]
 [ 8  9 10]]
2
int64
(2, 3)


### Indexing & slicing arrays

Indexing and slicing 1D arrays (vectors) is similar to indexing lists.

You can index matrices using `[row,column]`. If you omit the column, it will give you the whole row.

If you use `:` for either row or column, it will give you all of those values.

In [ ]:
my_matrix[0,2]
#this would give us the first row and the third column

np.int64(3)

**Booleans** are variables that store `True` or `False`. They are named after the British mathematician George Boole. He first formulated Boolean algebra, which are a set of rules for how to reason with and combine these values. This is the basis of all modern computer logic.

We can also index arrays using Boolean operators or lists. When we use Booleans, we can think of this as filtering the array. For example:

In [ ]:
#intexing with an operator means i want every value greater than lets say 2

# Index with an operator
bool_matrix = my_matrix[my_matrix>2]

# Index with a list of coordinates
list_matrix = my_matrix[[0,1],[1,3]]

print(my_matrix) #this is printing out our original matrix
print(bool_matrix) #boolean matrix is equal to my matrix, and it pulls out numbers greater than 2.
print(list_matrix) #list matrix pulling (first row second column) and (second row fourth column)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[3 4 5 3 4 5]
[2 4]


><b>Task:</b> Create a variable called `my_boolean_matrix` that is equal to your `bool_matrix` variable, but with `dtype = 'bool'`. Print your `my_boolean_matrix` variable. What happened?




In [ ]:
# Your code here
print(bool_matrix.dtype) #type of the matrix

my_boolean_matrix = np.array([bool_matrix, bool_matrix], dtype = 'bool')
#my_boolean_matrix = bool_matrix.astype(bool) [we didnt learn this but it is another method]

print(my_boolean_matrix.dtype)

print(my_boolean_matrix)
#its giving all trues because all of our numbers are whole numbers greater than 0
#we didnt tell it to find numbers greater than 2 or anything so the default is numbers greater than 0

int64
bool
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


We can also change values in an array similar to how we would change values in a list. Run the code below, and then re-run the code with the second line un-commented.

In [ ]:
print(my_matrix)
my_matrix[0] = 8

my_matrix[0]
#turned the whole first row into 8s because we rename first row [0]
#because we didnt put another number it assumes we mean the whole row

[[8 8 8 8 8]
 [1 2 3 4 5]]


array([8, 8, 8, 8, 8])

### Benefits of using arrays

In addition to being less clunky & a bit faster than lists of lists, arrays can do a lot of things that lists can't. For example, we can add and multiply them. Alternatively, we can use the `sum` method to sum across a specific axis.

In [ ]:
sum_list = [1,3,5] + [3,5,7]
sum_array = np.array([1,3,5]) + np.array([3,5,7])
mult_array = np.array([1,3,5]) * np.array([3,5,7])

print(sum_list)
print(mult_array)

#when you add two lists together, it concationates the two lists together
#when you muliply using numpy, it multiplies the columns together

[1, 3, 5, 3, 5, 7]
[ 3 15 35]


In [ ]:
this_array = np.array([[1,3,5],[3,5,7]])
sum_rows = this_array.sum(axis=1)
print(this_array)
print(sum_rows)

#when you sum the rows with axis = 1 you get 9 and 15
#the first dimension is rows, the second dimension is columns. so when you tell it axis is 1 it goes across the second demsion which is columns
#adds the columns together in each row
#across the columns in the first row you get 9 [1+3+5=9]
#across the columns in the second row you get 15 [3+5+7=15]

#if you change the axis to 0, it adds across rows. you probably get [1+3 =4 3+5=8 5+7=12]

sum_rows = this_array.sum(axis=0)
print(sum_rows)

[[1 3 5]
 [3 5 7]]
[ 9 15]
[ 4  8 12]


### Numpy also includes some very useful array generating functions:

* `arange`: like `range` but gives you a useful numpy array, instead of an interator, and can use more than just integers
* `linspace` creates an array with given start and end points, and a desired number of points
* `logspace` same as linspace, but in log.
* `random` can create a random list
* `concatenate` which can concatenate two arrays along an existing axis
* `hstack` and `vstack` which can horizontally or vertically stack arrays

Whenever we call these, we need to use whatever name we imported numpy as (here, `np`).

In [ ]:
# When using linspace, both end points are included!
np.linspace(0,147,10)

#linspace gives you an array of a specified number of values, so if you want an array of 10 values and the first number is o, all the way to 147
#it will give you 10 equally spaced values between these specified numbers

array([  0.        ,  16.33333333,  32.66666667,  49.        ,
        65.33333333,  81.66666667,  98.        , 114.33333333,
       130.66666667, 147.        ])

>**Task**: Create an array called `big_array` that has two rows. The first row should be a list of 10 numbers that are evenly spaced, and range from exactly 1 to 100. The second row should be a list of 10 numbers that begin at 0 and are exactly 10 apart (*hint*: use [np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)). `big_array` should have a shape (2,10): two rows, and ten columns. Lastly, reassign the last value of each row in the array to be -100.

In [ ]:
# Your code here
#big array should have 2 rows, 10 columns, then change the last number in each row to -100

big_array = np.array([np.linspace(1,100, 10), np.arange(start=0, stop=100, step=10)])

print(big_array)
print(big_array.shape)

#changing the last numbers to -100
big_array[0,-1] = -100
big_array[1,-1] = -100

print(big_array)

#filtering out any numbers less than 50
bool_array = big_array[big_array > 50]
print(bool_array)

[[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90.]]
(2, 10)
[[   1.   12.   23.   34.   45.   56.   67.   78.   89. -100.]
 [   0.   10.   20.   30.   40.   50.   60.   70.   80. -100.]]
[56. 67. 78. 89. 60. 70. 80.]
